### ISSUE TITLE
T+相关接口直接返回JSON数组，导致无法接收返回数据

### ISSUE THREAD

**Issue by nadirvishun** [Chanjet/chanjet-openapi-java-sdk#1]
最近在调用T+相关接口，发现好多接口返回和文档中不一致，拿[查询存货](https://dev.chanjet.com/docs/tcloud/t+jcda/t+ch)来举例：
- 文档中的返回值是这样：
 ```
 result:[{"Code":"0101AS001","Name":"lw","Specification":"3","DefaultBarCode":""}]
 ```
- 实际返回值：
```
[{"Code":"0101AS001","Name":"lw","Specification":"3","DefaultBarCode":""}]
```
直接返回了`json数组`，缺少了`result`参数，导致继承自`ChanjetResponse`的相应类无法解析结果。而且如果出错的话，返回的又会是一个`json对象`，导致无法解析。
麻烦帮忙查看下如何解决？

-----
刚才看了下`demo`中的获取账套列表相关字段，发现可以用这种方式解决：
```
public class AccountBookListResponse<T extends AccountBook> extends ArrayList<T> implements ChanjetResponse, Serializable
```
那这样的话：
1. 文档描述有问题
2. 如果出错的话返回的又是个`json对象`，又不能解析到上方的列表中来了，只能靠捕获无法转换的错误来确定接口返回成功与否吗？
3. 虽然上方能获取到`AccountBookListResponse`，但要从这个list中取出`AccountBook`列表很麻烦，需要各种强制转换。

为什么这些接口不能和其它正常接口似的返回带有`code`,`message`,`result`的`json对象`来方便解析呢？

**Comment by zhangshuanc** [comment]
1、文档中的返回示例描述确实有问题，result:  这个是写文档的时候多复制了一部分，代表返回结果的意思，并不是响应报文的一部分。     
2、对于一些非json对象，或sdk无法处理的响应，你可以使用如下方法直接获取返回报文（而不是对象），判断返回结果
`HttpResponse doExecute(ChanjetRequest<ChanjetResponse> request)`
报错无法转换的问题是因为返回的成功报文和响应报文无法统一格式导致的，我们正在逐步通过改造API，使API更加规范。     
3、目前的API的返回格式还不统一，现在我们正在逐步改造API使API返回结构变得相同。   

感谢您提的宝贵建议，我们会将您提的意见统一评估后纳入到我们的API规范中，为您提供更好的API服务。

**Comment by nadirvishun** [comment]
@zhangshuanc  感谢解答。
关于`HttpResponse doExecute(ChanjetRequest<ChanjetResponse> request)`这个方法能否给出`request`和`response`这两个文件的示例？牵扯到泛型有点头疼。
